project:
  type: website
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: 
      - pulse
      - custom.scss
    toc: true
    toc-depth: 4
    highlight-style: custom.theme

website:
  favicon: favicon.ico
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    search: true
    left:
      - text: "Blog"
        href: https://benjaminwarner.dev
      - text: "Resources"
        menu:
          - text: fast.ai
            icon: link
            href: https://docs.fast.ai
          - text: fastcore
            icon: link
            href: https://fastcore.fast.ai
          - text: "Report an Issue"
            icon: bug
            href: https://github.com/warner-benjamin/fastxtend/issues
    right:
      - icon: github
        href: https://github.com/warner-benjamin/fastxtend/
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/benjamin_warner
        aria-label: Twitter
  sidebar:
    style: floating
    collapse-level: 3
  page-footer: 
    left: "Copyright © 2022 Benjamin Warner, MIT License" 
    right: 
      - icon: github
        href: https://github.com/warner-benjamin/fastxtend/
      - icon: twitter 
        href: https://twitter.com/benjamin_warner
  body-header: |
    <script src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon="{'token': '62f27bdcb8964407a52676798db9edfa'}" defer="defer"></script>


link-external-newwindow: true

metadata-files: [nbdev.yml, sidebar.yml]