project:
  type: website
  preview:
    browser: false

format:
  html:
    theme:
      - pulse
      - custom.scss
    toc: true
    toc-depth: 4
    highlight-style: custom.theme
    html-math-method: katex
    fontsize: 1.1rem
    grid:
      sidebar-width: 275px
      body-width: 1025px
      margin-width: 275px
      gutter-width: 3rem

website:
  favicon: favicon.ico
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    search: true
    left:
      - text: "Blog"
        href: https://benjaminwarner.dev
      - text: "Resources"
        menu:
          - text: fast.ai
            icon: link
            href: https://docs.fast.ai
          - text: fastcore
            icon: link
            href: https://fastcore.fast.ai
          - text: nbdev
            icon: link
            href: https://nbdev.fast.ai
          - text: "Report an Issue"
            icon: bug
            href: https://github.com/warner-benjamin/fastxtend/issues
    right:
      - icon: github
        href: https://github.com/warner-benjamin/fastxtend/
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/benjamin_warner
        aria-label: Twitter
  sidebar:
    style: floating
    collapse-level: 2
  page-footer:
    left: "Copyright © 2023 Benjamin Warner, MIT License"
    right:
      - icon: github
        href: https://github.com/warner-benjamin/fastxtend/
      - icon: twitter
        href: https://twitter.com/benjamin_warner
  body-header: |
    <script src="https://static.cloudflareinsights.com/beacon.min.js?token=62f27bdcb8964407a52676798db9edfa" defer></script>

link-external-newwindow: true

metadata-files: [nbdev.yml, sidebar.yml]