name: nbdev-ci
on: [workflow_dispatch, push, pull_request]

jobs:
  nbdev-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/nbdev-ci@master
        with:
          skip_test: true

  nbdev-tests:
    needs: nbdev-sync
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py: ['3.8', '3.9', '3.10']
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py }}
        architecture: 'x64'
        cache: "pip"
        cache-dependency-path: settings.ini

    - name: Install Library
      run: |
        sudo apt-get install libsndfile1-dev
        pip install --upgrade pip
        pip install -e .[dev]

    - name: Run Tests
      run: |
        nbdev_test