name: nbdev-ci
on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
        architecture: 'x64'
  
    - name: Activate python cache
      uses: actions/cache@v3
      env:
        cache-name: pip-packages
      with:
        path: |
          ${{ env.pythonLocation }}
          ${{ env.pip-packages }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}

    - name: Install the library
      run: |
        sudo apt-get install libsndfile1-dev
        pip install --upgrade pip
        pip install -e .[dev]

    - name: Check that notebooks are clean
      run: |
        nbdev_clean
        git status -s # display the status to see which nbs need cleaning up
        if [[ `git status --porcelain -uno` ]]; then
          git status -uno
          echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"
          false
        fi

    - name: Check that notebooks and library are in sync
      run: |
        nbdev_export
        if [[ `git status --porcelain -uno` ]]; then
          echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
          git status -uno
          git diff
          exit 1;
        fi

    - name: Run tests
      run: |
        nbdev_test