name: Deploy to GitHub Pages
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Install libsndfile1
      run: |
        sudo apt-get install libsndfile1-dev
    uses: fastai/workflows/quarto-ghp@master