name: Deploy to GitHub Pages
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cacheable Apt Install
        run: sudo apt-get update
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libsndfile1-dev libopencv-dev python3-opencv
          version: 1.0

      - name: Uncacheable Apt Install
        run: sudo apt-get install -y libturbojpeg-dev

      - name: Deploy Docs to GitHub Pages
        uses: fastai/workflows/quarto-ghp@master