name: Deploy to GitHub Pages
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Install Prerequisite
      run: |
        sudo apt-get install libsndfile1-dev
    - name: Deploy Docs to GitHub Pages
      uses: fastai/workflows/quarto-ghp@master